import {
  Activity,
  BadgeCheck,
  Banknote,
  Bitcoin,
  Brain,
  Briefcase,
  Building,
  Car,
  ChartCandlestick,
  ChartPie,
  Flame,
  Footprints,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  House,
  Landmark,
  Laptop,
  Layers,
  Medal,
  Milestone,
  PiggyBank,
  Plane,
  Search,
  Shield,
  Smartphone,
  Star,
  Store,
  Target,
  Trophy,
  Wallet,
  Zap,
  Baby,
  Dumbbell,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bitcoin: Bitcoin,
  brain: Brain,
  briefcase: Briefcase,
  building: Building,
  car: Car,
  candlestick: ChartCandlestick,
  pie: ChartPie,
  flame: Flame,
  footprints: Footprints,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  graduation: GraduationCap,
  heart: Heart,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  medal: Medal,
  milestone: Milestone,
  piggy: PiggyBank,
  plane: Plane,
  search: Search,
  shield: Shield,
  smartphone: Smartphone,
  star: Star,
  store: Store,
  target: Target,
  trophy: Trophy,
  wallet: Wallet,
  zap: Zap,
  baby: Baby,
  dumbbell: Dumbbell,
};

export function iconFor(key: string): LucideIcon {
  return ICONS[key] ?? Target;
}

export const GOAL_ICONS = ["shield", "house", "car", "plane", "graduation", "briefcase", "heart", "baby", "laptop", "smartphone", "gift", "piggy", "dumbbell", "target"];

export const GOAL_COLORS = ["#4F8CFF", "#A78BFA", "#34D399", "#FBBF24", "#F87171", "#22D3EE", "#F472B6", "#FB923C"];
