export interface GlossaryTerm {
  term: string;
  definition: string;
  example?: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { term: "Ação", definition: "Menor parte do capital de uma empresa. Quem compra ações vira sócio.", example: "Comprar PETR4 é comprar um pedacinho da Petrobras." },
  { term: "Alocação de ativos", definition: "Divisão do patrimônio entre classes de investimento, como renda fixa, ações, FIIs e exterior." },
  { term: "Aporte", definition: "Cada novo valor que você coloca nos investimentos.", example: "Aportar R$ 500 todo mês no Tesouro Selic." },
  { term: "B3", definition: "Bolsa de valores do Brasil, onde ações, FIIs, ETFs e BDRs são negociados." },
  { term: "BDR", definition: "Certificado negociado na B3 que representa ações de empresas estrangeiras.", example: "AAPL34 representa ações da Apple." },
  { term: "Benchmark", definition: "Índice de referência usado para comparar o desempenho de um investimento.", example: "O CDI é o benchmark da renda fixa." },
  { term: "Carteira", definition: "Conjunto de todos os seus investimentos." },
  { term: "CDB", definition: "Certificado de Depósito Bancário: você empresta dinheiro ao banco e recebe juros. Garantido pelo FGC." },
  { term: "CDI", definition: "Taxa de juros usada nos empréstimos entre bancos. Anda muito próxima da Selic e é referência da renda fixa." },
  { term: "Copom", definition: "Comitê de Política Monetária do Banco Central, que define a taxa Selic em 8 reuniões por ano." },
  { term: "Corretora", definition: "Instituição que dá acesso à bolsa e a outros investimentos." },
  { term: "Cotação", definition: "Preço atual de um ativo no mercado." },
  { term: "Custódia", definition: "Guarda dos seus ativos por uma instituição. No Tesouro Direto, a B3 cobra taxa de custódia de 0,20% ao ano." },
  { term: "DARF", definition: "Guia para pagamento de impostos federais, usada para pagar o IR sobre lucros na bolsa." },
  { term: "Day trade", definition: "Comprar e vender o mesmo ativo no mesmo dia. Tem IR de 20% sobre o lucro." },
  { term: "Debênture", definition: "Título de dívida emitido por empresas. As incentivadas são isentas de IR." },
  { term: "Diversificação", definition: "Distribuir o dinheiro entre ativos diferentes para reduzir riscos." },
  { term: "Dividend yield (DY)", definition: "Proventos pagos nos últimos 12 meses divididos pelo preço do ativo.", example: "DY de 6%: R$ 6 por ano para cada R$ 100 investidos." },
  { term: "Dividendos", definition: "Parte do lucro que a empresa distribui aos acionistas." },
  { term: "ETF", definition: "Fundo negociado na bolsa que replica um índice.", example: "BOVA11 replica o Ibovespa." },
  { term: "FGC", definition: "Fundo Garantidor de Créditos: protege até R$ 250 mil por CPF e por instituição em CDB, LCI, LCA e poupança." },
  { term: "FII", definition: "Fundo de Investimento Imobiliário. Investe em imóveis ou títulos do setor e costuma pagar rendimentos mensais." },
  { term: "Ibovespa", definition: "Principal índice da bolsa brasileira, formado pelas ações mais negociadas." },
  { term: "IFIX", definition: "Índice dos fundos imobiliários negociados na B3." },
  { term: "Inflação", definition: "Aumento geral dos preços ao longo do tempo." },
  { term: "IOF", definition: "Imposto sobre Operações Financeiras. Na renda fixa, incide sobre o rendimento em resgates com menos de 30 dias." },
  { term: "IPCA", definition: "Índice oficial de inflação do Brasil, calculado pelo IBGE." },
  { term: "JCP", definition: "Juros sobre Capital Próprio: forma de distribuir lucros com 15% de IR retido na fonte." },
  { term: "LCI / LCA", definition: "Letras de Crédito Imobiliário e do Agronegócio. Isentas de IR para pessoa física e garantidas pelo FGC." },
  { term: "Liquidez", definition: "Facilidade de transformar o investimento em dinheiro sem perder valor.", example: "Tesouro Selic tem alta liquidez; um imóvel, baixa." },
  { term: "Marcação a mercado", definition: "Atualização diária do preço de títulos de renda fixa conforme as taxas do mercado." },
  { term: "Preço médio", definition: "Média do preço pago em todas as suas compras de um mesmo ativo." },
  { term: "P/L", definition: "Preço da ação dividido pelo lucro por ação. Indica quantos anos de lucro 'pagam' o preço." },
  { term: "P/VP", definition: "Preço dividido pelo valor patrimonial por ação ou cota. Abaixo de 1, o mercado paga menos que o patrimônio contábil." },
  { term: "Pregão", definition: "Período em que a bolsa está aberta para negociações." },
  { term: "Renda fixa", definition: "Investimentos com regras de rendimento definidas na aplicação, como Tesouro e CDB." },
  { term: "Renda variável", definition: "Investimentos cujo retorno não é previsível, como ações, FIIs e cripto." },
  { term: "Reserva de emergência", definition: "Dinheiro para imprevistos, de 3 a 12 meses de gastos, em aplicação segura e com liquidez diária." },
  { term: "ROE", definition: "Retorno sobre o patrimônio: lucro dividido pelo patrimônio líquido. Mede a eficiência da empresa." },
  { term: "Selic", definition: "Taxa básica de juros da economia, definida pelo Copom." },
  { term: "Swing trade", definition: "Comprar e vender em dias diferentes. Vendas de ações até R$ 20 mil por mês têm lucro isento de IR." },
  { term: "Tesouro Direto", definition: "Programa para pessoas físicas comprarem títulos públicos federais. É o investimento mais seguro do país." },
  { term: "Ticker", definition: "Código de negociação de um ativo na bolsa.", example: "ITUB4, HGLG11, BOVA11." },
  { term: "Vacância", definition: "Percentual de imóveis sem inquilino em um FII." },
  { term: "Volatilidade", definition: "Intensidade com que o preço de um ativo sobe e desce." },
];
