export const INVOKE_CHANNELS = [
  "app:info",
  "auth:session",
  "auth:register",
  "auth:login",
  "auth:logout",
  "auth:changePassword",
  "auth:updateProfile",
  "users:list",
  "users:create",
  "users:update",
  "users:resetPassword",
  "users:delete",
  "cloud:sync",
  "plans:expense",
  "plans:export",
  "plans:wealth",
  "search:test",
  "voice:listen",
  "ai:logs",
  "ai:logs:clear",
  "backup:export",
  "backup:import",
  "data:getAll",
  "data:set",
  "notifications:list",
  "notifications:markRead",
  "notifications:remove",
  "notifications:clear",
  "alerts:state",
  "alerts:rearm",
  "market:quotes",
  "market:chart",
  "market:search",
  "market:indicators",
  "market:copom",
  "market:tesouro",
  "market:news",
  "market:selicHistory",
  "market:ipcaHistory",
  "portfolio:history",
  "banks:get",
  "learning:leaderboard",
  "ai:info",
  "ai:setConfig",
  "ai:catalog",
  "ai:test",
  "ai:chat",
  "ai:cancel",
  "reports:export",
  "deals:check",
  "deals:context",
  "window:setTheme",
  "shell:openExternal",
] as const;

export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];

export const EVENT_CHANNELS = ["notifications:new", "ai:event", "navigate", "data:changed", "session:ended"] as const;
export type EventChannel = (typeof EVENT_CHANNELS)[number];
