export const DAILY_TIPS: { title: string; message: string }[] = [
  { title: "Reserva primeiro", message: "Antes de investir em ações, tenha de 3 a 6 meses de gastos guardados em algo seguro e com resgate diário, como Tesouro Selic ou CDB com liquidez diária." },
  { title: "Juros compostos", message: "R$ 300 por mês a 10% ao ano viram cerca de R$ 60 mil em 10 anos — e quase R$ 24 mil disso são só juros. Tempo é o seu maior aliado." },
  { title: "FGC protege você", message: "CDB, LCI e LCA são garantidos pelo FGC até R$ 250 mil por CPF, por instituição. Bancos menores costumam pagar mais com a mesma garantia." },
  { title: "Cuidado com o rotativo", message: "Os juros do rotativo do cartão estão entre os mais altos do país. Quitar essa dívida rende mais do que qualquer investimento." },
  { title: "Diversificar é proteger", message: "Não coloque todo o dinheiro em um único ativo. Misture renda fixa, ações, FIIs e, se fizer sentido, uma pequena parte no exterior." },
  { title: "Poupança x CDB", message: "Com a Selic acima de 8,5%, a poupança rende 0,5% ao mês + TR. Um CDB de 100% do CDI costuma render bem mais, mesmo depois do IR." },
  { title: "Não tente adivinhar o mercado", message: "Investir todo mês, com disciplina, tende a funcionar melhor do que tentar acertar o momento exato de comprar." },
  { title: "Entenda o P/L", message: "O P/L mostra quantos anos de lucro seriam necessários para 'pagar' o preço da ação. Compare sempre com empresas do mesmo setor." },
  { title: "Dividend yield", message: "Um DY muito alto pode ser um alerta: às vezes o preço caiu por problemas na empresa. Olhe o histórico de lucros, não só o DY." },
  { title: "IR da renda fixa", message: "Quanto mais tempo você deixa o dinheiro aplicado, menor o imposto: de 22,5% (até 6 meses) para 15% (acima de 2 anos)." },
  { title: "LCI e LCA", message: "LCI e LCA são isentas de IR para pessoa física. Uma LCI de 90% do CDI pode render mais que um CDB de 105% em prazos curtos." },
  { title: "Isenção em ações", message: "Vendas de ações de até R$ 20 mil por mês (swing trade) são isentas de IR sobre o lucro. Acima disso, o imposto é de 15%." },
  { title: "FIIs pagam todo mês", message: "Fundos imobiliários costumam distribuir rendimentos mensais, isentos de IR para pessoa física dentro das regras. Ótimos para renda passiva." },
  { title: "Taxa de administração", message: "Em fundos, a taxa de administração é cobrada mesmo quando o fundo perde. Prefira fundos com taxas compatíveis com o que entregam." },
  { title: "Inflação come o dinheiro parado", message: "Com inflação de 5% ao ano, R$ 10 mil parados perdem cerca de R$ 500 de poder de compra em 12 meses." },
  { title: "Objetivos com prazo", message: "Separe seu dinheiro por objetivo: curto prazo em renda fixa com liquidez, longo prazo pode ter mais renda variável." },
  { title: "Golpes de 'retorno garantido'", message: "Desconfie de qualquer promessa de lucro alto e garantido. Confira se a empresa é autorizada pela CVM ou pelo Banco Central." },
  { title: "Tesouro IPCA+", message: "O Tesouro IPCA+ protege seu dinheiro da inflação e paga um juro real. Ótimo para aposentadoria — mas pode oscilar se vender antes do vencimento." },
  { title: "ETFs para começar", message: "Com um único ETF como o BOVA11, você investe nas maiores empresas da bolsa de uma vez. Simples e diversificado." },
  { title: "Rebalanceie", message: "Uma ou duas vezes por ano, confira se sua carteira continua com a divisão planejada entre renda fixa e variável." },
  { title: "Corte gastos pequenos", message: "Uma assinatura de R$ 40 por mês esquecida custa R$ 480 por ano. Revise suas assinaturas na aba Gastos." },
  { title: "Volatilidade é normal", message: "A bolsa sobe e desce todos os dias. Quedas fazem parte; o importante é a qualidade das empresas e o seu prazo." },
  { title: "Preço médio", message: "Comprar aos poucos ao longo do tempo cria um preço médio e reduz o risco de entrar tudo em um momento ruim." },
  { title: "Liquidez importa", message: "Antes de investir, veja quando você pode resgatar. Um CDB com vencimento em 3 anos pode não permitir saque antes." },
  { title: "Previdência privada", message: "Na previdência, compare as taxas e a tabela de IR (progressiva ou regressiva). Para prazos longos, a regressiva chega a 10%." },
  { title: "Cripto com moderação", message: "Criptomoedas são muito voláteis. Se quiser ter, use uma parte pequena da carteira e só depois de montar sua reserva." },
  { title: "Dólar como proteção", message: "Ter uma parte dos investimentos atrelada ao dólar (ETFs, BDRs) ajuda a proteger seu patrimônio de crises no Brasil." },
  { title: "Taxa de corretagem", message: "Muitas corretoras já não cobram corretagem para ações e FIIs. Evite pagar taxas desnecessárias." },
  { title: "Dívida boa x ruim", message: "Financiar um curso que aumenta sua renda pode valer a pena; parcelar compras por impulso, quase nunca." },
  { title: "Selic e bolsa", message: "Quando a Selic cai, a renda fixa rende menos e a bolsa costuma ficar mais atrativa. Quando sobe, o contrário." },
  { title: "Comece pequeno", message: "Dá para começar com R$ 30 no Tesouro Direto ou com uma única cota de FII. O hábito vale mais que o valor inicial." },
  { title: "Leia o relatório", message: "Antes de comprar um FII, leia o relatório gerencial: vacância, inquilinos e prazo dos contratos dizem muito sobre o risco." },
  { title: "Metas visíveis", message: "Acompanhar suas metas no Investa todo mês aumenta a chance de você manter os aportes em dia." },
  { title: "Regra 50/30/20", message: "Uma divisão simples do salário: 50% para necessidades, 30% para desejos e 20% para investir e quitar dívidas." },
  { title: "Venda no pânico", message: "Vender tudo durante uma queda forte transforma uma perda temporária em perda real. Respire e revise seus motivos." },
  { title: "Juros sobre juros", message: "Reinvestir os dividendos e rendimentos acelera muito o crescimento do patrimônio no longo prazo." },
];
